[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Umbraco Documentation"
authors = [{name = "Sofie", email = "docs@umbraco.com"}]
dynamic = ["version", "description"]
